version: "3.9"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: tz6l8_ie2&=&9mrp+lb2k##13y66qw%c6o0k*z^io)y&#%fu%g
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:8000"
  postgres:
    environment:
      POSTGRES_PASSWORD: "Amir1343"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"

volumes: 
  postgres-data:

