// Common
export const UPDATE_ANY_ERROR = 'UPDATE_ANY_ERROR';
export const START_FETCHING = 'START_FETCHING';

// Get Current Profile
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

// Logout
export const USER_LOG_OUT = 'USER_LOG_OUT';
